### ISSUE TITLE
pass param to the connection

### ISSUE THREAD

**Issue by erichuang2015** [clue/reactphp-http-proxy#28]
Hello

I would like to use this lib to query domain whois server , for examle  the whois.nic.cx with port 43

$connector->connect('whois.nic.cx:43')->then(function (ConnectionInterface $stream) {
    $stream->on('data', function ($chunk) {
        echo $chunk;
    });
}, 'printf');

how can I pass domain name to this connection and get whois data back ?

**Comment by clue** [comment]
I'm not aware of any up-to-date whois library for ReactPHP. If you find any that works with recent ReactPHP versions, it should be just a matter of passing this proxy connector to this library.

If you want to implement the whois protocol yourself, I would recommend taking a look at https://github.com/reactphp-legacy/whois and others as a starting point :+1:
