### ISSUE TITLE
proxy not working with some servers

### ISSUE THREAD

**Issue by erichuang2015** [clue/reactphp-http-proxy#29]
Hello

I am using the proxy to connect to domain whois server to fetch results, it works well with most of the servers such as whois.nic.cx , whois.nic.gs etc

but it does not work with this whois server whois.nic.world ,this is my code reference url

https://paste.ofcode.org/kjHA8hYeX4QgSpHnbWwPzi

**Comment by clue** [comment]
Hi @erichuang2015, thanks for reporting!

We're not aware of any such issues and eyeballing the code you've provided, I can not see anything that is blatently wrong. Have you tried this without your proxy server and verified this works with another proxy server? It looks like you're writing just the domain name, but the WHOIS protocol suggests this should be terminated with a CRLF (`\r\n`), can you verify this?

> but it does not work with […]

What problem are you seeing exactly? Does it report an error message or how can we verify it "does not work"?

**Comment by erichuang2015** [comment]
I just run the code mentioned here https://paste.ofcode.org/kjHA8hYeX4QgSpHnbWwPzi

and then it will keep connecting to the whois server whois.nic.world till timeout , it will not show anything.

when I connect to whois server whois.nic.gs, all work fine, and it will get whois data back

do you have the codes  working for connecting whois server whois.nic.world:43, and get back the data ?

**Comment by erichuang2015** [comment]
I just run the code mentioned here https://paste.ofcode.org/kjHA8hYeX4QgSpHnbWwPzi

and then it will keep connecting to the whois server whois.nic.world till timeout , it will not show anything.

when I connect to whois server whois.nic.gs, all work fine, and it will get whois data back

do you have the codes working for connecting whois server whois.nic.world:43, and get back the data ?

I try several proxy ips and the problem still , it seems that the reactphp-http-proxy will not work if connect to new gtld whois servers.

**Comment by clue** [comment]
It looks like you're sending the wrong format.

You need to send `"hello.world\r\n"` instead of `"hello.world"` (note the trailing CRLF).

In other words: This is not an issue with this library, but an issue in your application code. This can be reproduced on the command line:

```bash
$ echo -en "hello.world\r\n" | nc whois.nic.world 43
$ echo -en "hello.world" | nc whois.nic.world 43
```

I hope this helps :+1:

**Comment by erichuang2015** [comment]
Hello

I tried to appendd the trailing CRLF and send "hello.world\r\n" to whois.nic.world:43, it the same issue mentioned above. it keep connecting to the whois server till timeout, I try serveral new gtld whois servers such as whois.nic.host whois.nic.run etc, and switch different proxy ips. 

even I send "hello.cx" to whois.nic.cx:43  without the trailing CRLF , it works fine and get the whois data back.

so, reactphp-http-proxy will not fetch the whois data back from new gtld domains, and it will only get the data from cctld domains,.

**Comment by clue** [comment]
In order to better understand the problem you're seeing, can you share an updated gist that highlights how your application code does work successfully when *not* using a proxy server and how it *breaks* when using a proxy server?

**Comment by erichuang2015** [comment]
Hi

https://paste.ofcode.org/kjHA8hYeX4QgSpHnbWwPzi 

this codes work perfect when query a cctld domain whois server such as 
whois.nic.cx 
whois.nic.gs
whois.nic.ms 
etc

but When I try to query a new gtld domain whois server, such as whois.nic.world , it will neither show whois data nor errors, just go to timeout and nothing happen
