### ISSUE TITLE
Use together reactphp-socks,reactphp-http-proxy?

### ISSUE THREAD

**Issue by Roundik** [clue/reactphp-http-proxy#30]
Hello!
Thanks for your code.
I am trying to do a quick check whois through a proxy.
Please tell me how can I use both classes of php proxies?
https://github.com/clue/reactphp-http-proxy/
 https://github.com/clue/reactphp-socks

I am new to react php, so if you give an example of the code I will be very grateful. For example, just get google.com whois data from whois.verisign-grs.com:43. :) 

Best regards, Roundik

**Comment by clue** [comment]
Hey @Roundik, welcome to @ReactPHP! :tada: 

This library allows you to create a connection to the destination server through an HTTP proxy server, i.e. it does not care about what application protocol you're using over this connection. This means you can use it for any application protocol, including whois.

If you're new to this project, I would suggest starting with one of the examples. You should be able to adjust for your application protocol. For whois, you simple send the domain name followed by CRLF like this and then read all the data until the connection is closed:

```php
$connection->write("clue.engineering\r\n");
```

I hope this helps you to get started :+1: 

*(If you need this for a commercial project and if you're interested in professional support, feel free to reach out and send me an email)*
