### ISSUE TITLE
Use as a standalone proxy server?

### ISSUE THREAD

**Issue by gamebak** [clue/reactphp-http-proxy#4]
Hello,

How we could use it as a standalone HTTP proxy server with https support as well ?

**Comment by clue** [comment]
Thanks for your interest! :+1:  This project currently (and in the future) only implements the client side.

If you're looking for a server side HTTP proxy implementation in PHP, make sure you're following my profile as this is something that I currently have in the pipeline :shipit:

**Comment by halfer** [comment]
I have a question for the Shipit Squirrel... how is this idea coming along? I have spent quite some time looking for a good quality PHP-based proxy library that supports TLS. I've found a few things that will do HTTP (e.g. `jenssegers/php-proxy`) but my understanding of the HTTPS conversation is probably not good enough to make a reliable solution for myself :smile_cat:

I shall quite understand if this has not yet been started. If you don't have any code for this, would anyone have any ten-second pointers as to libraries that might do this already?

**Comment by clue** [comment]
I'm actively working on this at this very moment, so stay tuned :-)

I have a working prototype locally and I'll make sure to publish this ASAP, but expected this to take ~4 weeks for the first public beta :shipit:

**Comment by halfer** [comment]
Splendid, many thanks @clue, I will keep a look-out. I have found [this script](http://stackoverflow.com/a/17040356) that looks like a good stop-gap in the meantime. Despite being a brief piece of code, it proxied a demo TLS site just fine.

**Comment by halfer** [comment]
Just for interest, [here is my current work](https://github.com/halfer/proximate-requester) - it's a play/record HTTP proxy with support for PSR-6 (for storage) and Guzzle middleware (to capture HTTPS sites). It'll be interesting to see if the listener part of my project can be easily replaced by your forthcoming package.
