### ISSUE TITLE
deprecated ringcentral/psr7 GitHub repository has been deleted

### ISSUE THREAD

**Issue by lucasnetau** [clue/reactphp-http-proxy#58]
compose installs of reactphp/http with dev dependencies is failing due to this package still relying on ringcentral/psr7. This repository was recently deleted from GitHub

**Comment by lucasnetau** [comment]
The only usage is RingCentral\Psr7\parse_response(). Guzzle\Psr7 library provides Message::parseResponse() providing the same functionality if you want to bring in that dependancy.

**Comment by SimonFrings** [comment]
Hey @lucasnetau thanks for opening this ticket, but are you sure this is the case? I can still find the [ringcentral/psr7 project on GitHub](https://github.com/ringcentral/psr7) and I can also install it via Composer locally. Can you confirm my findings?

FYI: Ultimately we want to move away from relying on the ringcentral/psr7 dependency and as this project only uses the `parse_response()` method, we might just implement a similar functionality in here.

**Comment by lucasnetau** [comment]
Looks like they restored it. It was a 404 response all day when browsing and composer install of reactphp/http was failing due to this dev dependency. This will break dev installs again if the repo is removed. 

See https://github.com/reactphp/http/issues/531

**Comment by SimonFrings** [comment]
Yeah, saw the 404 screenshot from https://github.com/reactphp/http/issues/531, maybe this was unintentional. I tried to look online and find something about this, but nothing. Hope this won't happen again, definitely one additional reason to move away from ringcentral/psr7.

I'll close this ticket now as I don't see much else to do here, thanks for bringing this to our attention @lucasnetau :+1:
